-- ============================================================
-- Olist Diagnostic Analysis: Downside Risk
-- ============================================================
-- Candidate population is generated by sql/04_diagnostic_region.sql.
-- No category x state values are hard-coded here.
-- ============================================================

CREATE OR REPLACE TEMP VIEW order_base AS
SELECT *
FROM read_parquet('data/processed/order_base.parquet');

CREATE OR REPLACE TEMP VIEW item_base AS
SELECT *
FROM read_parquet('data/processed/item_base.parquet');

CREATE OR REPLACE TEMP VIEW opportunity_candidates AS
SELECT *
FROM read_parquet('data/processed/opportunity_candidates.parquet');

-- ============================================================
-- 1. Candidate order population
-- Grain: 1 row = 1 category x state x order
-- ============================================================

CREATE OR REPLACE TEMP VIEW candidate_orders AS
SELECT DISTINCT
    i.product_category_name_english AS category,
    i.customer_state,
    i.order_id
FROM item_base i
JOIN opportunity_candidates c
  ON i.product_category_name_english = c.category
 AND i.customer_state = c.customer_state;

-- ============================================================
-- 2. Market benchmark
-- ============================================================

CREATE OR REPLACE TEMP VIEW market_risk AS
SELECT
    COUNT(*) FILTER (WHERE late_delivery_eligible) AS late_n,
    COUNT(*) FILTER (WHERE late_delivery_eligible AND late_delivery_flag) AS late_k,
    COUNT(*) FILTER (WHERE review_eligible) AS review_n,
    COUNT(*) FILTER (WHERE review_eligible AND review_score <= 2) AS low_review_k,
    1.0 * COUNT(*) FILTER (WHERE late_delivery_eligible AND late_delivery_flag)
      / NULLIF(COUNT(*) FILTER (WHERE late_delivery_eligible), 0) AS market_late_delivery_rate,
    1.0 * COUNT(*) FILTER (WHERE review_eligible AND review_score <= 2)
      / NULLIF(COUNT(*) FILTER (WHERE review_eligible), 0) AS market_low_review_rate
FROM order_base;

-- ============================================================
-- 3. Candidate operational risk
-- ============================================================

CREATE OR REPLACE TEMP VIEW candidate_operational_risk AS
SELECT
    c.category,
    c.customer_state,
    COUNT(*) AS orders,
    COUNT(*) FILTER (WHERE o.late_delivery_eligible) AS late_n,
    COUNT(*) FILTER (WHERE o.late_delivery_eligible AND o.late_delivery_flag) AS late_k,
    COUNT(*) FILTER (WHERE o.review_eligible) AS review_n,
    COUNT(*) FILTER (WHERE o.review_eligible AND o.review_score <= 2) AS low_review_k,
    1.0 * COUNT(*) FILTER (WHERE o.late_delivery_eligible AND o.late_delivery_flag)
      / NULLIF(COUNT(*) FILTER (WHERE o.late_delivery_eligible), 0) AS late_delivery_rate,
    AVG(o.review_score) FILTER (WHERE o.review_eligible) AS avg_review_score,
    1.0 * COUNT(*) FILTER (WHERE o.review_eligible AND o.review_score <= 2)
      / NULLIF(COUNT(*) FILTER (WHERE o.review_eligible), 0) AS low_review_rate
FROM candidate_orders c
JOIN order_base o USING (order_id)
GROUP BY 1, 2;

-- ============================================================
-- 4. Seller concentration
-- ============================================================

CREATE OR REPLACE TEMP VIEW candidate_seller_gmv AS
SELECT
    i.product_category_name_english AS category,
    i.customer_state,
    i.seller_id,
    SUM(i.merchandise_value) AS seller_gmv
FROM item_base i
JOIN opportunity_candidates c
  ON i.product_category_name_english = c.category
 AND i.customer_state = c.customer_state
WHERE i.order_purchase_timestamp >= TIMESTAMP '2018-02-01'
  AND i.order_purchase_timestamp <  TIMESTAMP '2018-09-01'
GROUP BY 1, 2, 3;

CREATE OR REPLACE TEMP VIEW candidate_seller_rank AS
SELECT
    *,
    ROW_NUMBER() OVER (
        PARTITION BY category, customer_state
        ORDER BY seller_gmv DESC
    ) AS seller_rank,
    SUM(seller_gmv) OVER (
        PARTITION BY category, customer_state
    ) AS total_gmv
FROM candidate_seller_gmv;

CREATE OR REPLACE TEMP VIEW candidate_concentration AS
SELECT
    category,
    customer_state,
    COUNT(*) AS seller_count,
    MAX(CASE WHEN seller_rank = 1 THEN seller_gmv / NULLIF(total_gmv, 0) END) AS top1_share,
    SUM(CASE WHEN seller_rank <= 3 THEN seller_gmv ELSE 0 END)
      / NULLIF(MAX(total_gmv), 0) AS top3_share
FROM candidate_seller_rank
GROUP BY 1, 2;

-- ============================================================
-- 5. Risk screen
-- Exclude only if BOTH operational rates are worse than market.
-- ============================================================

CREATE OR REPLACE TEMP VIEW candidate_risk_screen AS
SELECT
    r.*,
    c.seller_count,
    c.top1_share,
    c.top3_share,
    m.market_late_delivery_rate,
    m.market_low_review_rate,
    NOT (
        r.late_delivery_rate > m.market_late_delivery_rate
        AND r.low_review_rate > m.market_low_review_rate
    ) AS risk_eligible
FROM candidate_operational_risk r
JOIN candidate_concentration c USING (category, customer_state)
CROSS JOIN market_risk m;

SELECT
    category,
    customer_state,
    orders,
    late_n,
    ROUND(100 * late_delivery_rate, 2) AS late_delivery_rate_pct,
    ROUND(100 * market_late_delivery_rate, 2) AS market_late_delivery_rate_pct,
    review_n,
    ROUND(avg_review_score, 2) AS avg_review_score,
    ROUND(100 * low_review_rate, 2) AS low_review_rate_pct,
    ROUND(100 * market_low_review_rate, 2) AS market_low_review_rate_pct,
    seller_count,
    ROUND(100 * top3_share, 2) AS top3_seller_gmv_share_pct,
    risk_eligible
FROM candidate_risk_screen
ORDER BY risk_eligible DESC, category, customer_state;

COPY (
    SELECT *
    FROM candidate_risk_screen
)
TO 'data/processed/candidate_risk.parquet'
(FORMAT PARQUET);
